name: bench
on:
  push:
    branches:
      - master
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Setup Node
      uses: actions/setup-node@v2

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2

    - name: Setup Deno
      uses: denoland/setup-deno@v1

    - name: Install eleventy
      run: |
        cd ssg/eleventy
        npm install

    - name: Cache Ruby Bundler
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Install Jekyll
      run: |
        cd ssg/jekyll
        gem install bundler
        bundle update --bundler
        bundle config path vendor/bundle
        bundle install

    - name: Install lume
      run: |
        deno run -A https://deno.land/x/lume/install.js

    - name: Run the benchmarks
      run: |
        deno run --unstable -A cli.js --pages 1
        deno run --unstable -A cli.js --pages 10
        deno run --unstable -A cli.js --pages 100
        deno run --unstable -A cli.js --pages 1000
        deno run --unstable -A cli.js --pages 10000
