name: bench
on:
  push:
    branches:
      - master
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Setup Node
      uses: actions/setup-node@v2

    - name: Setup Ruby
      uses: actions/setup-ruby@v1

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2

    - name: Set Deno
      uses: denolib/setup-deno@v2

    - name: Install eleventy
      run: |
        cd ssg/eleventy
        npm install

    - name: Install Jekyll
      run: |
        cd ssg/jekyll
        gem install bundler
        bundle install

    - name: Run the benchmarks
      run: |
        deno run --unstable -A cli.js --pages 1
